### ISSUE TITLE
Cannot load library libcairo-2.dll

### ISSUE THREAD

**Issue by pdomenighetti** [poke1024/origami#14]
I proceeded to install Conda and origami; it appears that libcairo-2.dll is not generated because I got the following error (on Windows 10):

`(origami) C:\origami>python -m origami.batch.detect.segment
Traceback (most recent call last):
  File "C:\Users\Paolo\anaconda3\envs\origami\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Paolo\anaconda3\envs\origami\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\origami\origami\batch\detect\segment.py", line 8, in <module>
    from origami.batch.core.processor import Processor
  File "C:\Users\Paolo\anaconda3\envs\origami\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\origami\origami\batch\core\processor.py", line 29, in <module>
    from origami.batch.core.io import *
  File "C:\Users\Paolo\anaconda3\envs\origami\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\origami\origami\batch\core\io.py", line 21, in <module>
    from origami.core.block import Block, Line
  File "C:\Users\Paolo\anaconda3\envs\origami\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\origami\origami\core\block.py", line 18, in <module>
    from origami.core.mask import Mask
  File "C:\Users\Paolo\anaconda3\envs\origami\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\origami\origami\core\mask.py", line 4, in <module>
    from origami.core.canvas import Canvas
  File "C:\Users\Paolo\anaconda3\envs\origami\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\origami\origami\core\canvas.py", line 2, in <module>
    import cairocffi as cairo
  File "C:\Users\Paolo\anaconda3\envs\origami\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\Paolo\anaconda3\envs\origami\lib\site-packages\cairocffi\__init__.py", line 50, in <module>
    ('libcairo.so.2', 'libcairo.2.dylib', 'libcairo-2.dll'))
  File "C:\Users\Paolo\anaconda3\envs\origami\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e`

**Comment by pdomenighetti** [comment]
Apparently after swimming in the depths of Windows DLLs a simple `conda install cairo` in conda prompt solved the issue. I'll let this issue and close it for future users that could stumble into it.
