### ISSUE TITLE
Problem with model

### ISSUE THREAD

**Issue by a-wendler** [poke1024/origami#3]
`ERROR:root:Failed to process /media/dbsm-user/HD-WD-10021/1222231840/1046053973_04-03_00000016.tif.                       | 1/10 [00:16<02:27, 16.41s/it]
Traceback (most recent call last):
  File "/home/dbsm-user/Projekte/origami/origami/batch/core/processor.py", line 411, in _trigger_process1
    runtime_info = self.process(p, **kwargs)
  File "/home/dbsm-user/Projekte/origami/origami/batch/detect/segment.py", line 33, in process
    target=self._options["target"])
  File "/home/dbsm-user/Projekte/origami/origami/core/segment.py", line 119, in __init__
    ], models_path=models_path, grayscale=grayscale)
  File "/home/dbsm-user/Projekte/origami/origami/core/predict.py", line 118, in load
    loaded[name] = c(name, **kwargs)
  File "/home/dbsm-user/Projekte/origami/origami/core/predict.py", line 173, in __init__
    raise FileNotFoundError("no model file found at %s" % asset_path)
FileNotFoundError: no model file found at models/v3/sep/2/meta.json
`

I had to install Tensorflow via pip, because 2.1.2 is no longer available on conda. Could this be the problem?

**Comment by poke1024** [comment]
No, for some reason `models/v3/sep/2/meta.json` does not exist. I assume you used the model from https://www.dropbox.com/sh/7tph1tzscw3cb8r/AAA9WxhqoKJu9jLfVU5GqgkFa?dl=0 ?

In that case, this is strange, since `v3/sep/2/meta.json` should be included there.

The code producing the error above is really just a check if the file exists:

https://github.com/poke1024/origami/blob/36ef385664eda146bb44be6eb75584dfc6eb92f6/origami/core/predict.py#L170-L173

**Comment by a-wendler** [comment]
I downloaded again and now all the files are there. Don't know where the problem came from. Thx anyways
