### ISSUE TITLE
origami.tool.sample options problem

### ISSUE THREAD

**Issue by kouxichao** [poke1024/origami#5]
when i run ` python -m origami.tool.sample ./imgs` , error occurs. what makes this happen?
(origami) knowvision@knowvision-Z370-HD3:~/kxc/origami$ python -m origami.tool.sample ./imgs 
Traceback (most recent call last):
  File "/home/knowvision/miniconda3/envs/origami/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/knowvision/miniconda3/envs/origami/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/knowvision/kxc/origami/origami/tool/sample.py", line 204, in <module>
    sample_lines()
  File "/home/knowvision/miniconda3/envs/origami/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/knowvision/miniconda3/envs/origami/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/knowvision/miniconda3/envs/origami/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/knowvision/miniconda3/envs/origami/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/knowvision/kxc/origami/origami/tool/sample.py", line 198, in sample_lines
    processor = SampleProcessor(data_path, kwargs)
  File "/home/knowvision/kxc/origami/origami/tool/sample.py", line 50, in __init__
    super().__init__(options)
  File "/home/knowvision/kxc/origami/origami/batch/core/processor.py", line 269, in __init__
    self._debug_write = options["debug_write"]
KeyError: 'debug_write'

**Comment by poke1024** [comment]
@kouxichao This was a bug. Please try again with current master.
